services:
  app:
    image: node:22-alpine
    container_name: laravel_dev
    working_dir: /var/www
    ports:
      - "8000:8000"
      - "5173:5173"
    volumes:
      - .:/var/www
    entrypoint: >
      sh -c "
      apk add --no-cache php85 php85-cli php85-phar php85-openssl php85-mbstring 
      php85-tokenizer php85-xml php85-xmlwriter php85-session php85-pdo 
      php85-pdo_pgsql php85-pgsql php85-curl php85-dom php85-fileinfo php85-gd composer && 
      ln -sf /usr/bin/php85 /usr/bin/php && 
      composer dump-autoload && 
      composer install &&
      php artisan serve --host=0.0.0.0 --port=8000
      "
    networks:
      - dev-network

  postgres:
    image: postgres:16-alpine
    container_name: laravel_postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${DB_DATABASE:-laravel}
      POSTGRES_USER: ${DB_USERNAME:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - dev-network

networks:
  dev-network:
    driver: bridge

volumes:
  postgres_data:
    driver: local