services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dental_lab
    working_dir: /var/www
    volumes:
      - .:/var/www
    ports:
      - "8000:8000"
      - "5173:5173"